import Head from 'next/head';
import { useRouter } from 'next/router';
import React, { ReactNode } from 'react';
import { LayoutsFooterComponent } from './footer/layouts-footer.component';
import { LayoutsHeaderComponent } from './header/layouts-header.component';

export interface ILayoutsMain {
    title: string;
    children: ReactNode;
}

export const LayoutsMain: React.FC<ILayoutsMain> = (props: ILayoutsMain) => {
    const router = useRouter();
    return (
        <div>
            <Head>
                <title>{`${props.title} | HollowUI The Best Of UI Framework`}</title>
                <meta name="description" content="Generated by {props.title}" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <LayoutsHeaderComponent />
            <section>
                {props.children}
            </section>
            <LayoutsFooterComponent />
        </div>
    );
}